spring:
  application:
    name: edu-math-cms-service
  datasource:
    url: jdbc:mysql://localhost:3306/database
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 500
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  kafka:
    bootstrap-servers: localhost:9094
  ai:
    openai:
      api-key: jfgosa
      chat:
        options:
          model: gpt-4.0
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1/chat/completions
jhipster:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
  security:
    authentication:
      jwt:
        base64-secret: NTQxNjIwMjZmNzU1MmNmMzgwNzllMDYwMDUzNmRkMjQ5NTFmOTk5YTdkODIyYjY1M2Q1ZmJjYzBmYzdiOTVlMTE4MjgwNzEwODdiODUxM2FhNDE1ZTA2OTQ1MmZmNGE4NmNkOTE2Y2E0MTBjN2NmODM0OTdhNDA5Mzc0MjE4Yzg=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
    content-security-policy: "default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"
logging:
  level:
    org:
      springframework:
        security: DEBUG
server:
  port: 8080
  servlet:
    context-path: /edu-math
